### ISSUE TITLE
route is not working

### ISSUE THREAD

**Issue by UnrulyNatives** [ksassnowski/laravel-shareable-models#2]
There are some problems with documentation.

1) the entry to be put in the routes file has a typo:
```
Route::get('shared/{shareable_link}', ['middleware' => 'shared', function (ShareableLink $link) {
    return $link->shareable;
});
```
A closing bracket `]` is missing.

2) the route doesn't work anyway. To be honest I have no idea why.
I tried to link the route to middleware using an alternative syntax 
```
Route::get('shared/{shareable_link}', function (Sassnowski\LaravelShareableModel\Shareable\ShareableLink $link) {
    return 'test OK';
})->middleware('shared');
```
But to no result.

Maybe you could run the package on a clean new instance of Laravel 5.5?

3) In docs here `https://ksassnowski.gitbooks.io/shareable-models/content/getting-started.html`
it would be nicer if you mention that the user should declare the class in the header of the controller file:
`use Sassnowski\LaravelShareableModel\Shareable\ShareableLink;`

The package should be great, anyway! Thank you. 

Peter

**Comment by ksassnowski** [comment]
Hi Peter,

Your Route declaration looks correct at first glance. Not quite sure why it doesn't work for you. What error do you get? A 404? Have you registered the middleware in your kernel.php?

I'm on vacation at the moment and don't have my laptop with me. I will return on 23.09. Then I'll take a closer look at this. 

Kai

**Comment by johannesschobel** [comment]
Hey there.. 
I stumbled upon the same issues on my side.. However, I have a few more details on this issue (at least I think so):

I create a `ShareableLink` by using
```php
$link = ShareableLink::buildFor($user)
      ->setActive()
      ->setPrefix('users')
      ->build();
```

This should result in the following link
```
/shared/users/some_random_hash
```

However, if I `dd($link->url);` it only outputs:
```
/shared/users           // <-- notice the missing hash!
```

When calling the route directly in the browser and appending some hash, I `dd()`ed in the `ShareableLinkServiceProvider` as well.
In Line 23 you bind the `shareable_link` url segment and try to decode it. However, the value (e.g., the respective URL segment) is handed to the closure correctly.
The `$hashids` is created as well.. But the next line (line 27) returns `""` (empty string). Trying to retrieve a `ShareableLink` with this uuid - consequently - fails..

Hope this helps for digging into the problem!?

Cheers and have a nice vacation..

--------------

Update:
Sorry, forgot to mention the following things:
1) I am using Laravel 5.5.* (latest version)
2) In my application i am relying on `vinkla/hashIds`, which is basically another hashId package. Maybe this is related here as well? Don't think so, but better safe than sorry

**Comment by ksassnowski** [comment]
Hm that strange. I can't think of a reason why it should behave like that off the top of my head. Can someone maybe try and create a minimal repo that produces this error? 

I'll be back in Saturday or Sunday and will look into it then.

**Comment by johannesschobel** [comment]
The behavior I have described is not correct, right? The link->url should
contain the hash as well?

Maybe this is an issue specifically related to Laravel 5.5?

Sorry, I am on my way to vacation, can look into this next week..
hopefully..

Cheers

Am 19.09.2017 16:51 schrieb "Kai Sassnowski" <notifications@github.com>:

**Comment by johannesschobel** [comment]
Hey man, i'm back as well. If you like, we can "debug" this issue together.. So i can send you some code from my current project where this issue appears.. unfortunately, I do not have the time to make a minimal repo with this issue 😢

**Comment by ksassnowski** [comment]
I created a brand new Laravel 5.5 project and installed the package by following the documentation. I then copy and pasted your snippet from above to create a link for the default user model. If i then dump `$link->url` the link correctly contains the generated hash. I even added `vinkla/hashids` as a dependency just to see if there are conflicts. So I can't reproduce the error you seem to have on a clean project. I've uploaded my test repository [here](https://github.com/ksassnowski/shareable-link-issue). Check out the `routes/web.php`.

I still believe there could be a conflict by using `vinkla/hashids` in conjunction with this package but I haven't been able to reproduce the error. 

@johannesschobel Can you try and add a `dd(app()->make(Hashids\HashidsInterface::class))` somewhere in you application and post the output?

**Comment by ksassnowski** [comment]
@UnrulyNatives Do you by chance also use `vinkla/hashids` in your project?

**Comment by ksassnowski** [comment]
@johannesschobel Can you also post the output of doing a `dd(Ramsey\Uuid\Uuid::uuid4()->getHex())`? Because if that somehow produces an empty string then the created hash will also be empty which would result in the url you posted earlier `shared/users`.

**Comment by johannesschobel** [comment]
Hey man, awesome ideas.. I will try it tomorrow morning and give feedback
about the approaches..

Cheers and thank you very much

Am 25.09.2017 21:21 schrieb "Kai Sassnowski" <notifications@github.com>:

**Comment by johannesschobel** [comment]
Hey there,

ok, here is additional information from my project..
My code looks like this:

```php
$test = new ModelToShare();
$test->foo = 'hello';
$test->bar = true;
// ... 
$test->save();

dump($test);
dump(\Ramsey\Uuid\Uuid::uuid4()->getHex());

$link = ShareableLink::buildFor($test)
            ->setActive()
            ->build();

dump($link->url);
dd("ok");
```

This outputs:
```bash
ModelToShare {#1020 
// ,..
}

"c41a10e6310145f08f6dfe0397d8b1e7"
"http://api.api.dev/shared"
"ok"
```

Basically, the UUID using `Ramsey` is generated correctly.. 

My `ModelToShare` looks like this:
``` php
class ModelToShare extends AbstractShareLink { 
   // other stuff here
}
```
The `AbstractShareLink` model, however, looks like this:
``` php
// note the Model is the Laravel Eloquent Model Class!
abstract class AbstractShareLink extends Model implements ShareableInterface {
   use Shareable;
   // other stuff here
}
```

I am using an abstract class to "easily add" the `shareable` feature to my classes i want to share.. However, if i directly "add" it to the class, like so
```php
class ModelToShare extends Model implements ShareableInterface {
   use Shareable;
} 
```
this does not work either :(

Any ideas?! Thanks for helping out, man!
Cheers

**Comment by ksassnowski** [comment]
Even if I try to use an abstract base class like you did I can't reproduce the error.

What happens if you take the generated uuid from your example and manually do a 

```php
app()->make(HashidsInterface::class)->encodeHex('c41a10e6310145f08f6dfe0397d8b1e7')
```
Does that output a hash?

**Comment by ksassnowski** [comment]
Can you also take a look at your `shareable_links` table in your database and check if the `hash` column is empty? Maybe something goes wrong when building the url, not when generating the hash.

**Comment by johannesschobel** [comment]
for me, this line
```php
$hash = app()->make(HashidsInterface::class)->encodeHex($uuid);
```
(`\Sassnowski\LaravelShareableModel\Shareable\ShareableLinkBuilder`, Line 114)
returns `""` (empty)... Even with a previously generated uuid..

**Comment by johannesschobel** [comment]
if i 
```php 
dump(app()->make(HashidsInterface::class));
```

this outputs the following:
```bash
Hashids {#1069
  #alphabet: "abcd" // changed here
  #seps: "abcd" // changed here
  #guards: "abcd" // changed here
  #minHashLength: 16
  #salt: "base64:+abcd=" // changed here
}
```

so i guess, the application can create a class from the given interface. However, the method-call does nt work :(

**Comment by ksassnowski** [comment]
[This issue might be related](https://github.com/ivanakimov/hashids.php/issues/61). Are you on a Mac by any chance?

**Comment by johannesschobel** [comment]
no, windows computer.. i'll take a look at this issue in a few minutes..

**Comment by johannesschobel** [comment]
a tuple in my `shareable_link` table looks like this:
```
id = 1
active = 1
shareable_id = 5
shareable_type = App\...\ModelToShare
url = http://api.api.dev/shared
uuid = 0f98a1ef2cf64c6b97fa00fafde50fc2 
hash = "" // empty!
password = null
// date fields here
```

**Comment by ksassnowski** [comment]
Ok, so something is going wrong when encoding the uuid. I'm not on a windows machine so I can't test it right now. It might have something to do with a missing php package. What's the output of running `function_exists('gmp_div_q')` on your machine?

**Comment by ksassnowski** [comment]
The Hashids readme notes

> Note: Hashids requires the BCMath extension in order to work. Optionally you can use the GMP extension.

Is either of those packages installed? Can you run

```bash
php -i | grep bcmath
```

**Comment by johannesschobel** [comment]
a `dd(function_exists('gmp_div_q'));` returns `false` on my machine..

```bash
>php -i | grep bcmath
bcmath
bcmath.scale => 0 => 0
```

Do i need to install another dependency?
Cheers

**Comment by johannesschobel** [comment]
but i don't understand this problem.. my `vinkla/hashids` package requires `hashids/hashids`.. and `hashids/hashids` requires `ext-bcmath`..

`vinkla/hashids`, however, works on my machine.. so this should work!? I don't get it 😕

**Comment by ksassnowski** [comment]
Yeah this is weird since `vinkla/hashids` is really just a Laravel wrapper around `hashids/hashids`. I might have to fire up a Windows VM later and try to debug it. I'm running out of ideas.

**Comment by ksassnowski** [comment]
Can you try if 

```php
app()->make(HashidsInterface::class)->encodeHex('aa');
```

returns a hash? You might be running into a `PHP_MAX_INT` error where the generated UUID is too large for your system to handle.

**Comment by johannesschobel** [comment]
damn.. replacing `$uuid` with `'aa'` worked for me..
Thank you soooooo much for helping out!

Would you fix this "globally" in your package? Or what would be the best idea to deal with this?

**Comment by ksassnowski** [comment]
Unfortunately this seems to be a bigger problem that's not as easy to fix. The issue is that I'm passing a de-hyphenated UUID to the Hashid's `encodeHex` method. The UUID might exceed `PHP_MAX_INT` however (especially on 32-bit systems) which is then causing your error. Hashing a UUID looks like the wrong approach. I have to spent a bit of time researching. Sorry that I can't offer an immediate solution.

Any help on this is greatly appreciated.

**Comment by johannesschobel** [comment]
hmmmmmmmmmm.. I'm not sure if i understand the problem correctly..
I am running this on a 32bit Windows machine

If i can do anything (e.g., send you some debug information) to help you with this issue, just let me know.. 

I'm crossing fingers that you solve this issue.. your shareable-model plugin looks really nice and i really would love to use it in my application!

**Comment by ksassnowski** [comment]
> hmmmmmmmmmm.. I'm not sure if i understand the problem correctly..

Let's say the UUID I generate is `eb2dea54-a14f-4198-8f0e-333eaa17d7a8`. If I de-hyphenate it I end up with the hexadecimal `eb2dea54a14f41988f0e333eaa17d7a8`. If you convert this number to base 10 you end up with a really, really large number. That number exceeds `PHP_MAX_INT`. On 32-bit systems `PHP_MAX_INT` is `2147483647`. The `decodeHex` method first tries to convert the hexadecimal to a base 10 integer and then tries to encode that. However, that conversion fails which then causes `encode` to return an empty string.

I can think of two possible solutions to this problems, both of which would require a major version bump.

1. Skip the Hashid completely and simply use the UUID in the url. Less configurable, not as pretty (arguably) but it would solve this problem.

2. Use the database autoincrement ID and hash that instead of the uuid. This would require two writes to the database however since I first would have to save the model to get an ID and then update the model after I generated the hashid from the ID.

I'm strongly leaning towards option 1. I will look into this tonight when I get home.

**Comment by johannesschobel** [comment]
ah, ok - now i get it..
why not a

3. create a random "hash" using a `generateRandomString()` method and use this one?

**Comment by ksassnowski** [comment]
My main reservation about that is the chance of collisions. With UUIDs at least I know that the chances of a collision are astronomically unlikely. If I use, say, Laravel's `str_random` I'm not quite sure about the randomness guarantees. I'd have to pick a long enough string at which point I might just use a UUID.

**Comment by johannesschobel** [comment]
yeah, i know your point.. Let's see what you come up with.. If i can help you with anything, let me know..

**Comment by ksassnowski** [comment]
I just uploaded a new version to the develop branch. Can you check it using `"sassnowski/laravel-shareable-models": "dev-develop"` in your `composer.json`?

**Comment by johannesschobel** [comment]
Hey there,
Thank you so much for your time and efforts on this..

I will try tomorrow or on Wednesday, ok? I will give you feedback regarding the generated link and hash?! What other information do you need?

Best,
Johannes

**Comment by ksassnowski** [comment]
Hopefully the only feedback you will give me is that it now works :)

**Note:** You might have to run `php artisan migrate` before you try it again since I had to add a new migration.

**Comment by johannesschobel** [comment]
I'll find out ;) .. Will happily give feedback on this

**Comment by johannesschobel** [comment]
you are a beast.. it works ;)
Thank you very much for your time and efforts! Really awesome work..

However, i noticed few things, maybe you can clarify those aspects?
1) You are now using `doctrine/dbal` - do you really need this? Because this adds a lot of dependencies to the project
2) Is it possible to customize the `baseurl` of the package? Because i don't want to use the `shared/` but rather `v1/shared/`- where can i customize this? Because the generated link automatically sets `shared/`.. And i am only able to declare `prefixes` for the `uuid` (but this is added between `shared` and the `uuid`).

Thank you so much!
Cheers,
Johannes

**Comment by ksassnowski** [comment]
Glad to hear its working now. I tagged version 2.0.0 just now.

Regarding your points:

- I moved `doctrine/dbal` to the dev dependencies since its needed to drop columns on sqlite databases
- You can configure the base url in config by changing the `base_url` key.

Kai

**Comment by johannesschobel** [comment]
awesome.. thanks for adding the `base_url` to the config file! I like it!
Thanks for your support!
Johannes
