### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by johannesschobel** [ksassnowski/laravel-shareable-models#4]
There is a typo in this migration file on the `2.0.0.` tag that has been fixed in an earlier version of this package but now was re-introduced.

https://github.com/ksassnowski/laravel-shareable-models/blob/a0ca34d83d9133612a6974ad18f22ddb2de3c218/database/migrations/2017_08_30_200213_add_should_notify_column_to_shareable_links_table.php#L29

it is fixed on `dev-master`, though i prefer to use a specific version in my `composer.json` file. Furthermore, using `migrate:refresh` is not valid on the `2.0.0` tag! ;)

Cheers

**Comment by ksassnowski** [comment]
Thanks for the issue. I just tagged version 2.0.1 that contains the correct migration. Sorry about the regression.

**Comment by johannesschobel** [comment]
Thanks a lot
