### ISSUE TITLE
QueryException with invalid UUID

### ISSUE THREAD

**Issue by filipegar** [ksassnowski/laravel-shareable-models#6]
Hello.

I've been testing your package to replace dwightwatson/autologin on my project and tried to supply an invalid uuid value to the url.
The project is running with a postgres database, that have native field support to uuids. In this case, laravel throws a Illuminate\Database\QueryException. 

To solve this, I added a try/catch block to the Route::bind call on the ServiceProvider as below:
The idea is to replace the QueryException with the ModelNotFoundException, that will be handled by Laravel and will generate a proper 404 response.

```php
<?php

Route::bind('shareable_link', function ($value) {
    try {
	return ShareableLink::where('uuid', $value)->firstOrFail();
    } catch(QueryException $e) {
	throw new ModelNotFoundException($e->getMessage());
    }
});
```

Do you have a better approach to this? May I open a pull request?

**Comment by ksassnowski** [comment]
Hi, thanks for opening this issue.

I like your solution. I'd be happy if you'd open a pull request.
